sudo: true
dist: trusty

notifications:
  slack:
    secure: vrIQgoWk6vxxlXh42Y8CpMT+I7l0zvqiE08sHWO6aRTDF6imxzbjfUxfXvw1Ge0w8lH6YGywz6vTNRT9IA0eznCCt8pIJvhu4hCbFevdWKzIG5b+rf/lNCbxzugfTbY54ddAaG9aFo1R4ebJD70amJvFYp0yLr3VSYKuMTuxOX70yWPLQBNtxSIP/WIGJJY6vMMpCsygjRQLndrzQgA8MGrW6pKUdg8Y5C4p+V5grDuPjTWL6XLPzHJQZeE/xDsGWT302xZnyqMgC3xKoEiOPoGN2FGem6zcaT9SowyczmNjGxGQO/2LQPAxvhVtE+dsE4CQwCqxJM1bJXPrMTCaeiTi6MPNsR8zPXr8pyXjbn5qyYEvdZ0kUQrX4lUhYv0kJH5LfzUWSIzpQyxuJkt6PYTq+dX5MNeLVFyiDf1vZmsdGVFI/LJfKxI/6LtF4U9C8/C5G4wQZK2fs3QifkL9rqTDzrF1c+7x53Mqzohx9FNe8cU5PWZzpmNpZMwOwmA4mKBzCkxhwiyPGrY2ofHRTw4cRt7uIkdq09BUOHAeKGCUkWwLgvqz+A+vTc+9fr9MV9NYU1xpmMqq+1FFwnEu7+vm1XCrIMa5av9LyV2WkdI7sas2TmYyLFdSOFePUVCcLrt3zm2xkXSh2bzdZR85T71Rm/x3VVjBSBsYgIb/hgQ=
    on_success: always
    on_failure: always

env:
  global:
    - secure: "Co3mkARdc+qmROA+5zxKbj0tGa+hiQDNJDt8RDNqr43xCRNh187ku73/b+lHXLDuzmeI7NNilw15U/uapj5auD2FHsmtJvNtqoydgjDISDuwizE1aL0G5dhrSkbg/cU8WOWpe/3cQW92ub1lSbuRclJOAfkxZh8qL9NTUPWn0JKm+AkbJVYFzhXUNUe/zcPcN+e4Gbb/IbB1kGsZgCfh9Vbm1GGno0iIjX2smydsF+UFs+ALBs6wQiSc8KoMNLof+KmYsORg99OHYXgQM89QxfaMZFcHTEiDDrsUax1BK49+F98BBLOd9SgB2pQtU3UeYLiv9IY4xN9pWokLx3qZfBB8Rj8fNyyFGnClDrgPWgO3KNmAMoXwmKFEprJPgUU462v+RyE+JdC62Clj6hsft8e9TvYqXol5nBrLkSWvwGSji0s8TzLDuFiwt0f1mXYM8/m1/DKjou9E21T6zYICyng+TrhBHzdjhDj0JBGHu2VQQVj7OmPeBhlse10YlUJ6mMA6Wz/sLjfLO20GaCE2NNjkZ7ypxa5HuIIncBEBDJ90MD5tZYJuBUjHPlLhi61zbjzI7YEA7TTrplsAmDvNC+PZeIk0POzvJE2OARNCp7fxvVHcLdWWMiuM34kG057vwW9Zwbo4uE8dlky+rb+y4fHC7QGsmb8k2p+jbOKiKSY="

install:
- npm install -g doctoc
- gem install mdl

script:
- cat handbook/*/README.md > handbook/README.md
- doctoc handbook/README.md
- mdl handbook/README.md > handbook/mdl.txt
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config credential.helper "store --file=.git/credentials"
- git commit -a -m 'Update README.md (via Travis-CI) [ci skip]'
- git push origin HEAD:master
